name: Build PDF from LaTeX
on:
  workflow_dispatch:
  pull_request:
    branches: [master]
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install and setup Nix
        uses: cachix/install-nix-action@v23
      - name: Configure Nix to use the devenv cache
        uses: cachix/cachix-action@v12
        with:
          name: devenv
      - name: Install devenv
        run: nix profile install --accept-flake-config tarball+https://install.devenv.sh/latest
      - name: Build devenv shell and run any pre-commit hooks
        run: devenv ci
      - name: Build cheatsheet PDF file
        run: make
      - uses: actions/upload-artifact@v4
        with:
          name: Cheatsheet
          path: cheatsheet.pdf
          if-no-files-found: error
